# NON GRADED CHALLENGE 6 - Linear Algebra (Eigendecomposition)

### Assignment Objectives

Non-Graded Assignment ini di buat guna menge valuasi konsep Linear Algebra sebagai berikut:
- Memahami konsepe igen value dan eigen vector
- Dapat mencari eigen value dan eigen vector


### Assignment Instructions

Apakah [1,3 ]adalah eigenvector dari [[1 ,-1],[6 4 ]]? Jika iya, berapakah eigenvalue-nya?

In [6]:
import numpy as np
from numpy.linalg import eig

In [2]:
A=np.array([[1,-1],[6,4]])
A

array([[ 1, -1],
       [ 6,  4]])

In [3]:
# define matrix
B=np.array([1,3])
B


array([1, 3])

In [4]:
A @ B/B

array([-2.,  6.])

untuk nilai -2 dan 6 bukan eigenvector dari [[1 ,-1],[6 4 ]]